# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-12 22:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work_week', '0002_auto_20170812_2114'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('extra_orders', models.PositiveSmallIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=85, max_digits=7)),
                ('menu', models.CharField(blank=True, max_length=150)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_week.Day')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
