# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-12 23:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_details', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='users',
            new_name='user',
        ),
    ]
