# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-13 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_details', '0003_auto_20170813_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=85, max_digits=10),
        ),
    ]
