# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-15 09:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_details', '0004_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_week.Day'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
