# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_details', '0010_auto_20170821_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='day',
        ),
    ]
