# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_details', '0011_remove_order_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
