# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-12 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyplan',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
