# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-13 22:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_plan', '0004_auto_20170813_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyplan',
            name='day',
        ),
    ]
