# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-12 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_week', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['pk']},
        ),
    ]
