# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-13 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_week', '0002_auto_20170812_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
