# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-12 19:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('type', models.IntegerField(choices=[(1, 'Once'), (2, 'Custom')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_time', models.TimeField()),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Cancelled')])),
                ('sunday', models.NullBooleanField(default=False)),
                ('monday', models.NullBooleanField(default=False)),
                ('tuesday', models.NullBooleanField(default=False)),
                ('wednesday', models.NullBooleanField(default=False)),
                ('thursday', models.NullBooleanField(default=False)),
                ('friday', models.NullBooleanField(default=False)),
                ('saturday', models.NullBooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Plan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
